apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-06-01T05:57:54Z"
  name: myminio-hl
  namespace: minio-tenant
  ownerReferences:
  - apiVersion: minio.min.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: myminio
    uid: 73361242-ac8e-4f4b-b0e8-4d3332c5200e
  resourceVersion: "80464277"
  uid: b250f763-da14-4715-9069-80b34e8bf315
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-minio
    port: 9000
    protocol: TCP
    targetPort: 9000
  publishNotReadyAddresses: true
  selector:
    v1.min.io/tenant: myminio
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
