apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-patcher-binding
subjects:
- kind: ServiceAccount
  name: pv-patcher-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pv-patcher
  apiGroup: rbac.authorization.k8s.io
