apiVersion: batch/v1
kind: Job
metadata:
  name: pv-patcher-job
  namespace: default
spec:
  ttlSecondsAfterFinished: 172800  # 2 days in seconds
  template:
    spec:
      serviceAccountName: pv-patcher-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.30.7
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting PV patching job"

          kubectl get pv -o name | while read -r pv; do
            echo "Patching $pv"
            if kubectl patch "$pv" -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'; then
              echo "Patch successful for $pv"
              policy=$(kubectl get "$pv" -o jsonpath='{.spec.persistentVolumeReclaimPolicy}')
              echo "$pv new persistentVolumeReclaimPolicy: $policy"
            else
              echo "Failed to patch $pv"
            fi
          done

          echo "PV patching job completed"
      restartPolicy: Never
  backoffLimit: 4
