apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  annotations:
    meta.helm.sh/release-name: verlero
    meta.helm.sh/release-namespace: velero
  labels:
    app.kubernetes.io/instance: verlero
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: velero
    helm.sh/chart: velero-10.0.1
  name: local-minio
  namespace: velero
spec:
  accessMode: ReadWrite
  config:
    insecureSkipTLSVerify: "true"
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://10.43.134.69:80
  credential:
    key: credentials-velero
    name: cloud-credentials
  default: true
  objectStorage:
    bucket: velero
  provider: aws
